---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: sts-annotator
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sts-annotator
rules:
  - apiGroups:
      - "*"
    resources:
      - pods
      - statefulsets
    verbs:
      - get
      - list
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sts-annotator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sts-annotator
subjects:
  - kind: ServiceAccount
    name: sts-annotator
    namespace: default