name: sts-annotator
namespace: default


k8s:
  url: https://kubernetes.default.svc
  token: /run/secrets/kubernetes.io/serviceaccount/token
  tls:
    caCert: /run/secrets/kubernetes.io/serviceaccount/ca.crt

app:
  logLevel: info



config:
  logLevel: info


  k8s:
    url: https://kubernetes.default.svc
    token: /run/secrets/kubernetes.io/serviceaccount/token
    tls:
      caCert: /run/secrets/kubernetes.io/serviceaccount/ca.crt

  server:
    mode: release
    log:
      level: info
    port: 8443
    tls:
      cert: /run/secrets/sts-annotator/server.crt
      key: /run/secrets/sts-annotator/server.key

  k8s:
    url: https://kubernetes.default.svc
    token: /run/secrets/kubernetes.io/serviceaccount/token
    tls:
      caCert: /run/secrets/kubernetes.io/serviceaccount/ca.crt