---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}
type: Opaque
data:
  server.crt: {{ required "Missing '.Values.tls.cert'. A valid base64 encoded server certificate entry is required." .Values.tls.cert }}
  server.key: {{ required "Missing '.Values.tls.key'. A valid base64 encoded server private key entry is required." .Values.tls.key }}
