apiVersion: apps/v1
kind: Deployment
metadata:
  name: sts-annotator
  namespace: <REPLACE HERE BY YOUR NAMESPACE>
  labels:
    app: sts-annotator
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sts-annotator
      version: v1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sts-annotator
        version: v1
    spec:
      serviceAccount: sts-annotator
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - sts-annotator
                topologyKey: kubernetes.io/hostname
              weight: 100
      containers:
        - name: sts-annotator
          image: "docker.io/mkikyotani/sts-annotator:2"
          imagePullPolicy: Always
          ports:
            - name: https
              containerPort: 8443
              protocol: TCP
          env:
            - name: TZ
              value: Asia/Tokyo
          volumeMounts:
            - name: tls
              mountPath: /run/secrets/sts-annotator
            - name: app-config
              mountPath: /sts-annotator/config.yaml
              subPath: config.yaml
          resources:
            limits:
              cpu: 20m
              memory: 25Mi
            requests:
              cpu: 20m
              memory: 25Mi
          livenessProbe:
            httpGet:
              scheme: "HTTPS"
              path: /v1/healthz
              port: 8443
            initialDelaySeconds: 3
            periodSeconds: 3
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              scheme: "HTTPS"
              path: /v1/healthz
              port: 8443
            initialDelaySeconds: 3
            periodSeconds: 3
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
        - name: tls
          secret:
            secretName: sts-annotator
        - name: app-config
          configMap:
            name: sts-annotator