apiVersion: v1
kind: Service
metadata:
  labels:
    app: sts-annotator
  name: sts-annotator
  namespace: default
spec:
  selector:
    app: sts-annotator
  type: ClusterIP
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8443
